cache:
  address: '192.168.0.64'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1

jwt:
  access_token_secret: 'access_token_secret'
  refresh_token_secret: 'refresh_token_secret'

app:
  port: ':9100'
  cert_file: './cmd/api/certificate.pem'
  key_file: './cmd/api/key.pem'
  time_format: '2006-01-02T15:04:05'

health:
  port: ':8290'
  shutdown_endpoint: '/api/v1/superhero_auth_health/shutdown'
  content_type: 'application/json'